### ISSUE TITLE
examples need adapting from pymudokon to hydraxmpm

### ISSUE THREAD

**Issue by chyalexcheng** [GrainLearning/HydraxMPM#2]
Only the dam break (water) and two sphere impact examplse work now.

**Comment by chyalexcheng** [comment]
@Retiefasaurus 2bdffa335d62f6aea78a2e3104515d65c8a8b188

**Comment by Retiefasaurus** [comment]
please see if code runs in `tutorial/t1_granular_column.py`. And check if documentation works.

Install dev dependencies
`uv sync --dev`

serve documents on port `http://127.0.0.1:8000`
`mkdocs serve`

**Comment by Retiefasaurus** [comment]
Output directories are not added to the git repo, 

please add
`tutorials/output/t1_pack`
`tutorials/output/t1_collapse`
